#!/bin/csh

# This job requests number_of_tasks MPI tasks (without OpenMP)
#SBATCH -n 30
#SBATCH -t 00:01:00
#SBATCH -p test
#SBATCH -o ./out/output.%j.out # STDOUT

module purge
module load slurm/current
module load gcc/11.2
module load openmpi/4.1.1

mpirun ./wetP