#include "CentralXYZ.hh"
#include "CentralXYZNoSolid.hh"
#include "CentralXYZInterfaceNoSolid.hh" //Still need to do
#include "Laplacian.hh"
#include "LaplacianNoSolid.hh"
#include "CentralQ.hh"
#include "CentralQNoSolid.hh"
#include "CentralXYZFourthOrder.hh"
#include "LaplacianFourthOrder.hh"
#include "MixedXYZ.hh"
#include "MixedXYZNoSolid.hh"
#include "MixedQ.hh"
#include "MixedQNoSolid.hh"