#!/bin/sh

# This job requests number_of_tasks MPI tasks (without OpenMP)
# SBATCH -N 1
#SBATCH -n 4
#SBATCH -c 4
#SBATCH -t 00:01:00
# SBATCH --ntasks-per-socket=8
#SBATCH -p test
#SBATCH -o ./out/output.%j.out # STDOUT
export OMP_NUM_THREADS=4
mpirun ./wetP
#./wetP