#!/bin/sh

# This job requests number_of_tasks MPI tasks (without OpenMP)
# SBATCH -N 1
#SBATCH -n 1
#SBATCH -c 8
#SBATCH -t 00:01:00
# SBATCH --ntasks-per-socket=1
#SBATCH -p test
#SBATCH -o ./out/output.%j.out # STDOUT
export OMP_NUM_THREADS=8
mpirun ./wetP
# ./wetP